// MESSAGE -----------------------------------------------------
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE'

// STUDENTS -----------------------------------------------------
export const FETCH_STUDENTS = 'FETCH_STUDENTS'
export const FETCH_STUDENTS_START = 'FETCH_STUDENTS_START'
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS'
export const FETCH_STUDENTS_FAIL = 'FETCH_STUDENTS_FAIL'

export const CREATE_STUDENT = 'CREATE_STUDENT'
export const CREATE_STUDENT_START = 'CREATE_STUDENT_START'
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS'
export const CREATE_STUDENT_FAIL = 'CREATE_STUDENT_FAIL'

export const DELETE_STUDENT = 'DELETE_STUDENT'
export const DELETE_STUDENT_START = 'DELETE_STUDENT_START'
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS'
export const DELETE_STUDENT_FAIL = 'DELETE_STUDENT_FAIL'

export const UPDATE_STUDENT = 'UPDATE_STUDENT'
export const UPDATE_STUDENT_START = 'UPDATE_STUDENT_START'
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS'
export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL'


// LOGS -----------------------------------------------------
export const FETCH_LOGS = 'FETCH_LOGS'
export const FETCH_LOGS_START = 'FETCH_LOGS_START'
export const FETCH_LOGS_SUCCESS = 'FETCH_LOGS_SUCCESS'
export const FETCH_LOGS_FAIL = 'FETCH_LOGS_FAIL'

export const CREATE_LOG = 'CREATE_LOG'
export const CREATE_LOG_START = 'CREATE_LOG_START'
export const CREATE_LOG_SUCCESS = 'CREATE_LOG_SUCCESS'
export const CREATE_LOG_FAIL = 'CREATE_LOG_FAIL'

export const DELETE_LOG = 'DELETE_LOG'
export const DELETE_LOG_START = 'DELETE_LOG_START'
export const DELETE_LOG_SUCCESS = 'DELETE_LOG_SUCCESS'
export const DELETE_LOG_FAIL = 'DELETE_LOG_FAIL'

export const UPDATE_LOG = 'UPDATE_LOG'
export const UPDATE_LOG_START = 'UPDATE_LOG_START'
export const UPDATE_LOG_SUCCESS = 'UPDATE_LOG_SUCCESS'
export const UPDATE_LOG_FAIL = 'UPDATE_LOG_FAIL'
